
name: Nightly Build Rustdesk for fireworld

on:
  #schedule:
    # schedule build every night
    # - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  run-flutter-nightly-build:
    uses: ./.github/workflows/fireworld-build.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: "nightly"
