name: Nightly Build Android for fireworld

on:
  #schedule:
    # schedule build every night
    # - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: 'release tags(Default:1.4.7)'
        required: true
        default: '1.4.8'

jobs:
  run-flutter-nightly-build:
    uses: ./.github/workflows/android-build.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: "${{ inputs.upload-tag }}"
