name: Auto merge Submodules

on:
  workflow_dispatch:

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update Submodules
        run: |
          git config --global user.email "avkiller2012@gmail.com"
          git config --global user.name "avkiller"
          git submodule update --init --recursive
          git submodule update --recursive --remote
          cd libs/hbb_common
          git fetch --all
          git submodule foreach 
          git fetch --prune
          cd ..
          git checkout -b rustdesk-master master
          git pull https://github.com/rustdesk/rustdesk.git master
          
          
      - name: Check for changes
        id: check_changes
        run: |
          # echo "::set-output name=changes::$(git status --porcelain)"
          echo "changes=$(git status --porcelain)" >> $GITHUB_OUTPUT
      - name: Commit and push changes
        if: steps.check_changes.outputs.changes != ''
        run: |
          git add libs/hbb_common
          git add .
          git checkout master
          git merge --no-ff rustdesk-master
          git commit -m "merge submodules"
          git push
