name: Update Submodules

on:
  #push:
  #  branches:
  #    - main
  #schedule:
  #  - cron: '0 0 * * *'  # 每天UTC时间0:00执行
  workflow_dispatch:

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update Submodules
        run: |
          git config --global user.email "avkiller2012@gmail.com"
          git config --global user.name "avkiller"
          git subtree pull --prefix=libs/hbb_common https://github.com/avkiller/hbb_common.git main --squash --message="updatelib"
          # git submodule update --init --recursive
          # git submodule update --recursive --remote
          # 备份当前修改（如有）
          # git checkout master
          # git rm -r libs/hbb_common
          # git commit -m "Remove subtree to reset history"
          # git subtree add --prefix=libs/hbb_common https://github.com/avkiller/hbb_common.git main --squash
          # git add libs/hbb_common
          git add .
          git commit --no-verify -m "Update submodules"
          git status
          git push origin master

